import { Purchase, Car, PurchaseState, CarCondition, TimeFilterType, Employee, ClientType, ComponentStatus } from './types';

export const mockEmployees: Employee[] = [
  { id: '1', name: 'Daniel Kuruc', role: 'Manažer' },
  { id: '2', name: 'Matej Decky', role: 'Obchodní zástupce' },
  { id: '3', name: 'Jana Novakova', role: 'Inspektor' },
];

export const mockCars: Car[] = [
  {
    id: '1',
    make: 'BMW',
    model: '320d',
    year: 2019,
    vin: 'WBA3A5G59DNP26082',
    color: 'Černá',
    mileage: 85000,
    fuelType: 'Nafta',
    engineSize: '140 kW',
    transmission: 'Automatická',
    condition: CarCondition.USED,
    bodyType: 'Sedan',
    driveType: 'Zadní',
    stk: '12/2025',
    firstRegistration: '03/2019',
    isImport: false,
    isFirstOwner: false,
    hasServiceBook: true,
    hasSecurityScrews: true,
    hasAiWheels: false,
  },
  {
    id: '2', 
    make: 'Audi',
    model: 'A4 Avant',
    year: 2020,
    vin: 'WAUZZZ8K6LA123456',
    color: 'Bílá',
    mileage: 45000,
    fuelType: 'Benzín',
    engineSize: '110 kW',
    transmission: 'Automatická',
    condition: CarCondition.USED,
    bodyType: 'Kombi',
    driveType: 'Přední',
    stk: '06/2026',
    firstRegistration: '09/2020',
    isImport: true,
    isFirstOwner: true,
    hasServiceBook: true,
    hasSecurityScrews: false,
    hasAiWheels: true,
  },
  {
    id: '3',
    make: 'Mercedes-Benz',
    model: 'C 220d',
    year: 2021,
    vin: 'WDD2050012R123456',
    color: 'Stříbrná',
    mileage: 25000,
    fuelType: 'Nafta',
    engineSize: '147 kW',
    transmission: 'Automatická',
    condition: CarCondition.USED,
    bodyType: 'Sedan',
    driveType: 'Zadní',
    stk: '01/2027',
    firstRegistration: '02/2021',
    isImport: false,
    isFirstOwner: true,
    hasServiceBook: true,
    hasSecurityScrews: true,
    hasAiWheels: true,
  }
];

const componentStatuses1: ComponentStatus[] = [
  { component: 'Motor', status: 'good', notes: 'Běží plynule' },
  { component: 'Převodovka', status: 'excellent' },
  { component: 'Brzdy', status: 'fair', notes: 'Potřeba výměna destiček' },
  { component: 'Podvozek', status: 'good' },
  { component: 'Karoserie', status: 'good', notes: 'Drobné škrábance na zadním nárazníku' },
  { component: 'Interiér', status: 'excellent' },
  { component: 'Elektronika', status: 'good' },
  { component: 'Klimatizace', status: 'excellent' },
];

const componentStatuses2: ComponentStatus[] = [
  { component: 'Motor', status: 'excellent' },
  { component: 'Převodovka', status: 'excellent' },
  { component: 'Brzdy', status: 'good' },
  { component: 'Podvozek', status: 'excellent' },
  { component: 'Karoserie', status: 'good' },
  { component: 'Interiér', status: 'fair', notes: 'Opotřebení sedadla řidiče' },
  { component: 'Elektronika', status: 'good' },
  { component: 'Klimatizace', status: 'good' },
];

// Get today's date in YYYY-MM-DD format
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString().split('T')[0];

export const mockPurchases: Purchase[] = [
  {
    id: '1',
    clientName: 'Martin Svoboda',
    clientType: ClientType.PERSONAL,
    spz: 'BA123AB',
    purchaseDate: today,
    purchaseState: PurchaseState.COMPLETED,
    employeeId: '1',
    carDetails: mockCars[0],
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
    ],
    defectImages: [
      'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80',
    ],
    notes: 'Vozidlo ve výborném stavu. Potřeba menší servis brzd. Drobné škrábance na zadní levé dveři.',
    totalAmount: 485000,
    // Extended fields
    inspectionDate: '2024-01-14',
    customerPrice: 520000,
    offeredPrice: 485000,
    expectedSalePrice: 549000,
    isVatPayer: false,
    sourceKnowledge: 'Internet - Sauto.cz',
    isCounterAccount: false,
    vinVerified: true,
    phone: '+420 777 123 456',
    street: 'Hlavná 15',
    city: 'Bratislava',
    postalCode: '81101',
    componentStatuses: componentStatuses1,
  },
  {
    id: '2',
    clientName: 'AutoPro s.r.o.',
    clientType: ClientType.COMPANY,
    companyInfo: {
      companyName: 'AutoPro s.r.o.',
      ico: '12345678',
      dic: 'CZ12345678',
      address: 'Průmyslová 42, 01001 Žilina',
    },
    spz: 'ZA456CD',
    purchaseDate: today,
    purchaseState: PurchaseState.IN_PROGRESS,
    employeeId: '1',
    carDetails: mockCars[1],
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80',
    ],
    defectImages: [
      'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
    ],
    notes: 'Čeká na finální kontrolu a papírování. Klient je plátce DPH. Mírné poškození vozu na levé straně.',
    totalAmount: 628000,
    inspectionDate: '2024-01-17',
    customerPrice: 680000,
    offeredPrice: 628000,
    expectedSalePrice: 719000,
    isVatPayer: true,
    sourceKnowledge: 'Doporučení',
    isCounterAccount: true,
    vinVerified: true,
    phone: '+420 903 456 789',
    street: 'Průmyslová 42',
    city: 'Žilina',
    postalCode: '01001',
    componentStatuses: componentStatuses2,
  },
  {
    id: '3',
    clientName: 'Peter Novak',
    clientType: ClientType.PERSONAL,
    spz: 'TT789EF',
    purchaseDate: yesterday,
    purchaseState: PurchaseState.NEW,
    employeeId: '1',
    carDetails: mockCars[2],
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    ],
    notes: 'Nová žádost o výkup. Hodnocení vozidla čeká.',
    totalAmount: 785000,
    inspectionDate: '2024-01-21',
    customerPrice: 850000,
    offeredPrice: 785000,
    expectedSalePrice: 899000,
    isVatPayer: false,
    sourceKnowledge: 'Facebook reklama',
    isCounterAccount: false,
    vinVerified: false,
    phone: '+420 911 222 333',
    street: 'Nová 8',
    city: 'Trnava',
    postalCode: '91701',
    componentStatuses: [
      { component: 'Motor', status: 'excellent' },
      { component: 'Převodovka', status: 'excellent' },
      { component: 'Brzdy', status: 'excellent' },
      { component: 'Karoserie', status: 'excellent' },
      { component: 'Interiér', status: 'excellent' },
    ],
  },
  {
    id: '4',
    clientName: 'Anna Krejcova',
    clientType: ClientType.PERSONAL,
    spz: 'KE321GH',
    purchaseDate: twoDaysAgo,
    purchaseState: PurchaseState.CANCELLED,
    employeeId: '3',
    carDetails: {
      id: '4',
      make: 'Volkswagen',
      model: 'Golf',
      year: 2018,
      vin: 'WVWZZZ1KZAW123456',
      color: 'Červená',
      mileage: 95000,
      fuelType: 'Benzín',
      engineSize: '81 kW',
      transmission: 'Manuální',
      condition: CarCondition.USED,
      bodyType: 'Hatchback',
      driveType: 'Přední',
      stk: '08/2024',
      firstRegistration: '05/2018',
      isImport: true,
      isFirstOwner: false,
      hasServiceBook: false,
      hasSecurityScrews: false,
      hasAiWheels: false,
    },
    notes: 'Výkup zrušen kvůli problémům s financováním klienta.\nDůvod zrušení: Nedohoda o ceně',
    totalAmount: 218000,
    inspectionDate: '2024-01-11',
    customerPrice: 250000,
    offeredPrice: 218000,
    expectedSalePrice: 259000,
    isVatPayer: false,
    sourceKnowledge: 'Opakovaný zákazník',
    isCounterAccount: false,
    vinVerified: true,
    phone: '+420 905 111 222',
    street: 'Kvetná 23',
    city: 'Košice',
    postalCode: '04001',
    componentStatuses: [
      { component: 'Motor', status: 'fair', notes: 'Vyšší spotřeba oleje' },
      { component: 'Převodovka', status: 'good' },
      { component: 'Brzdy', status: 'poor', notes: 'Nutná výměna' },
      { component: 'Karoserie', status: 'damaged', notes: 'Promáčklina na dveřích' },
    ],
  }
];

export const defaultPurchaseFilter = {
  employeePurchasesOnly: false,
  todayPurchases: false, // DEPRECATED - use timeFilter instead
  timeFilter: TimeFilterType.ALL,
  purchaseStateFilter: [PurchaseState.NEW, PurchaseState.IN_PROGRESS, PurchaseState.COMPLETED],
  clientName: '',
  spz: '',
  employeeName: ''
};