// Vehicle selection options for New Purchase form

export const VEHICLE_MAKES = [
  'Abarth', 'Acura', 'Alfa Romeo', 'Alpina', 'Aston Martin', 'Audi', 
  'Bentley', 'BMW', 'Brilliance', 'Bristol', 'Bugatti', 'BYD',
  'Cadillac', 'Changan', 'Chery', 'Chevrolet', 'Chrysler', 'Citroen', 'Corvette',
  'Cupra', 'Dacia', 'Daewoo', 'Daihatsu', 'De Tomaso', 'Donkervoort', 'Dunkels',
  'Ferrari', 'Fiat', 'Fisker', 'Ford', 'Foton', 'Frazer Nash',
  'Geely', 'Genesis', 'Gillet', 'Ginetta', 'GMC', 'Gumpert',
  'Haval', 'Hawtai', 'Hongqi', 'Hummer', 'Hyundai',
  'Infiniti', 'Isuzu', 'Iveco',
  'Jaguar', 'Jeep', 'Jianghuai', 'Joust', 'JMC',
  'Kia', 'Koenigsegg', 'Kymco',
  'Lada', 'Lamborghini', 'Lancia', 'Land Rover', 'Landwind', 'Lark', 
  'Lexus', 'Lifan', 'Ligier', 'Lti', 'Lotus', 'Luxgen',
  'Mahindra', 'Maruti', 'Maserati', 'Maybach', 'Mazda', 'McLaren', 'Mercedes-Benz', 
  'Mercury', 'MG', 'Microcar', 'Mini', 'Mitsubishi', 'Monteverdi', 'Morgan', 'Morris',
  'Nanotech', 'Nissan', 'Noble', 'NSU',
  'Opel', 'Ora', 'Orus',
  'Pagani', 'Panhard', 'Panoz', 'Peugeot', 'Piaggio', 'Pininfarina', 'Plymouth', 
  'Pontiac', 'Porsche', 'Premier', 'Prince',
  'Qoros',
  'Radical', 'Raigun', 'RAM', 'Raize', 'Reliant', 'Renault', 'Reo', 'Revlon', 
  'Riley', 'Rimac', 'Rinspeed', 'Rolls-Royce', 'Rover', 'Ruf',
  'Saab', 'Saipa', 'Scion', 'Seagull', 'Seat', 'Sendra', 'Shuanghuan', 'SIAC',
  'Singer', 'Sizuki', 'Škoda', 'Smart', 'Spago', 'Spectre', 'Spyker', 'SRT',
  'SSC', 'Ssangyong', 'Subaru', 'Sungbeam', 'Suzuki', 'Swallow',
  'Talbot', 'Tata', 'Tesla', 'Tianma', 'Tiarin', 'Tiema', 'Tiger', 'Torino',
  'Tosca', 'Toyota', 'Trabant', 'Tramontana', 'Triton', 'Triumph', 'TVR', 'Tvornica',
  'Twike',
  'Ultima', 'Unipro',
  'Vandenbrink', 'Vanderhall', 'Vanimal', 'Vaseauto', 'Venturi', 'Veritas',
  'Verse', 'Vignale', 'Villard', 'Vinfast', 'Visas', 'Visteon', 'Volkswagen',
  'Volga', 'Volvo', 'Vorbei', 'Voxy',
  'Wagoneer', 'Wartburg', 'Westfield', 'Wiesmann', 'Willys', 'Wuling',
  'Xin', 'Xinkai',
  'Yangzi',
  'Youngtimer', 'Youxia',
  'Zanos', 'Zastava', 'Zenith', 'Zf', 'Zhonghua', 'Zotye', 'ZX', 'ZXY'
].sort();

export const VEHICLE_MODELS: Record<string, string[]> = {
  'Abarth': ['595', '124 Spider'],
  'Acura': ['ILX', 'MDX', 'RDX', 'TLX', 'NSX', 'RLX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', '4C', 'MiTo', '147', '156', '159', 'Mito'],
  'Alpina': ['B3', 'B4', 'B5', 'B6', 'B7', 'B11'],
  'Aston Martin': ['V8', 'DB9', 'DB11', 'DBS', 'Vantage', 'Rapide', 'AM29'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q4', 'Q5', 'Q7', 'Q8', 'e-tron', 'Q4 e-tron', 'e-tron GT', 'R8', 'TT', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7'],
  'Bentley': ['Flying Spur', 'Continental', 'Bentayga', 'Mulsanne', 'Azure'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'iX', 'M3', 'M4', 'M5', 'M550i', 'M440i', 'M340i'],
  'BYD': ['Yuan Plus', 'Song', 'Qin', 'Atto 3', 'Denza'],
  'Cadillac': ['CTS', 'XTS', 'XT4', 'XT5', 'XT6', 'Escalade', 'SRX', 'DTS'],
  'Changan': ['CS35', 'CS55', 'CS75', 'UNI', 'Eado'],
  'Chery': ['Tiggo 2', 'Tiggo 4', 'Tiggo 5', 'Tiggo 7', 'Tiggo 8', 'A1', 'A3'],
  'Chevrolet': ['Aveo', 'Cruze', 'Lacetti', 'Spark', 'Captiva', 'Equinox', 'Traverse', 'Malibu', 'Corvette', 'Camaro', 'Silverado'],
  'Chrysler': ['Pacifica', '300', 'Sebring', 'PT Cruiser', 'Town & Country'],
  'Citroen': ['C1', 'C3', 'C4', 'C5', 'C6', 'Berlingo', 'Jumpy', 'C3 Aircross', 'C5 Aircross', 'SpaceTourer', 'Ami'],
  'Cupra': ['Formentor', 'Leon', 'Ateca'],
  'Dacia': ['Sandero', 'Duster', 'Logan', 'Dokker', 'Lodgy', 'Spring', 'Jogger'],
  'Daewoo': ['Lanos', 'Lacetti', 'Matiz', 'Nexia', 'Nubira'],
  'Daihatsu': ['Charade', 'Copen', 'Materia', 'Terios', 'Boon'],
  'Donkervoort': ['D8', 'S8A'],
  'Ferrari': ['F8', '812', 'FF', 'F430', 'F450', '488', 'California', 'LaFerrari', 'Roma', 'SF90'],
  'Fiat': ['500', '500C', '500X', '500L', 'Panda', 'Tipo', 'Punto', 'Bravo', 'Doblo', 'Multipla', '600', '126'],
  'Fisker': ['Karma', 'Ocean'],
  'Ford': ['Fiesta', 'Focus', 'Mondeo', 'Taurus', 'Mustang', 'Ranger', 'F-150', 'F-250', 'Transit', 'Transit Connect', 'Galaxy', 'S-Max', 'Kuga', 'Edge', 'Explorer', 'Puma', 'EcoSport', 'Tourneo'],
  'Foton': ['Tunado', 'Sauvage', 'T8', 'Bigpai'],
  'Geely': ['Emgrand', 'Kingkong', 'Boyue', 'Coolray', 'X6'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'Gillet': ['Vertigo'],
  'Ginetta': ['G40', 'G50', 'G55', 'G60'],
  'GMC': ['Sierra', 'Yukon', 'Terrain', 'Acadia', 'Canyon'],
  'Haval': ['H1', 'H2', 'H3', 'H4', 'H6', 'H7', 'H8', 'H9'],
  'Hawtai': ['Dahuang', 'Shuma', 'Shuomai'],
  'Hongqi': ['H5', 'H7', 'H9', 'HS5', 'HS7'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Fit', 'Odyssey', 'Pilot', 'Ridgeline', 'Insight', 'Jazz', 'e', 'CR-Z', 'S2000', 'Prelude'],
  'Hummer': ['H1', 'H2', 'H3', 'EV'],
  'Hyundai': ['i10', 'i20', 'i30', 'i40', 'Elantra', 'Sonata', 'Grandeur', 'Tucson', 'Santa Fe', 'Venue', 'Creta', 'Kona', 'IONIQ', 'Nexo', 'Prius', 'ix20', 'ix35'],
  'Infiniti': ['Q30', 'Q50', 'Q60', 'Q70', 'Q80', 'QX30', 'QX50', 'QX55', 'QX60', 'QX80', 'FX', 'EX'],
  'Isuzu': ['D-Max', 'MU-X', 'Trooper', 'Rodeo', 'Picking'],
  'Iveco': ['Daily', 'S-Way', 'Stralis', 'EuroCargo'],
  'Jaguar': ['XE', 'XF', 'XJ', 'I-PACE', 'E-PACE', 'F-PACE', 'XK', 'F-Type', 'X-Type'],
  'Jeep': ['Renegade', 'Compass', 'Wrangler', 'Cherokee', 'Grand Cherokee', 'Gladiator'],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'K3', 'Forte', 'Optima', 'K5', 'Stinger', 'Sportage', 'Sorento', 'Niro', 'EV6', 'EV9', 'Stonic', 'Telluride', 'Venga', 'Carens'],
  'Koenigsegg': ['Agera', 'Gemera', 'Jesko'],
  'Lamborghini': ['Huracán', 'Aventador', 'Urus', 'Revuelto'],
  'Lancia': ['Lybra', 'Thesis', 'Dedra', 'Delta', 'Integrale', 'Y'],
  'Land Rover': ['Discovery', 'Range Rover', 'Evoque', 'Velar', 'Sport', 'Defender', 'Freelander'],
  'Lexus': ['ES', 'GS', 'LS', 'LC', 'CT', 'UX', 'NX', 'RX', 'GX', 'LX', 'HS', 'NX450h', 'RX450h'],
  'Lifan': ['X50', 'X60', 'X70', '320', '530', '620', '720'],
  'Lotus': ['Emira', 'Evora', 'Exige', 'Elise', 'Esprit'],
  'Lti': ['TX'],
  'Mahindra': ['XUV300', 'XUV500', 'Bolero', 'Scorpio', 'Thar', 'Marazzo'],
  'Maruti': ['Swift', 'Celerio', 'Ignis', 'Vitara Brezza', 'Ertiga', 'Baleno'],
  'Maserati': ['Ghibli', 'Levante', 'Quattroporte', 'MC20', 'Grecale'],
  'Maybach': ['S-Class', '57', '62'],
  'Mazda': ['2', '3', '5', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-90', 'MX-5', 'MX-30', 'CX-7'],
  'McLaren': ['570S', '720S', '765LT', 'GT', 'Senna', 'Speedtail'],
  'Mercedes-Benz': ['A', 'B', 'C', 'ML', 'GL', 'CLA', 'CLS', 'E', 'S', 'GL', 'GLA', 'GLB', 'GLC', 'GLE', 'GLK', 'GLS', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'AMG GT', 'SL', 'SLC', 'V-Class', 'Vito', 'Sprinter'],
  'MG': ['ZS', 'RX5', 'GS', 'RX8', '6', 'Hector', 'Astor'],
  'Mini': ['Cooper', 'Cooper S', 'Countryman', 'Clubman', 'Paceman', 'One', 'Cooper D'],
  'Mitsubishi': ['ASX', 'Outlander', 'Outlander PHEV', 'Eclipse Cross', 'Pajero Sport', 'Pajero', 'L200', 'Space Star', 'i-MiEV', 'Lancer'],
  'Morgan': ['Plus Four', 'Plus Six', '3-Wheeler', 'Aero'],
  'Morris': ['Minor', 'Oxford'],
  'Nissan': ['Micra', 'Sentra', 'Altima', 'Maxima', 'Rogue', 'Murano', 'Pathfinder', 'Leaf', 'Leaf Plus', 'Ariya', 'GT-R', 'Qashqai', 'Juke', 'X-Trail', 'T32', 'Note', 'Versa', 'Frontier', 'Navara', 'Pulsar'],
  'Opel': ['Corsa', 'Astra', 'Insignia', 'Grandland', 'Crossland', 'Mokka', 'Grandland X', 'Meriva', 'Zafira', 'Adam', 'Karl', 'Combo', 'Vivaro'],
  'Ora': ['Good Cat', 'Black Cat', 'Funky Cat'],
  'Pagani': ['Huayra', 'Zonda', 'Huayra Roadster'],
  'Panhard': ['CD', 'PL17'],
  'Peugeot': ['107', '206', '207', '208', '301', '307', '308', '309', '405', '406', '407', '508', '2008', '3008', '5008', 'Partner', 'Rifter', 'Traveller', 'Expert', 'Boxer'],
  'Piaggio': ['Ape', 'Porter'],
  'Plymouth': ['Neon', 'Voyager', 'Prowler'],
  'Pontiac': ['G5', 'G6', 'G8', 'Solstice', 'Grand Am'],
  'Porsche': ['911', 'Boxster', 'Cayman', 'Panamera', 'Cayenne', 'Macan', 'Taycan'],
  'Qoros': ['3', '5', 'GQ3', 'GQ5'],
  'Radical': ['SR3', 'SR8'],
  'RAM': ['1500', '2500', '3500', 'ProMaster'],
  'Renault': ['Clio', 'Megane', 'Laguna', 'Scenic', 'Grand Scenic', 'Captur', 'Kadjar', 'Koleos', 'Talisman', 'Twingo', 'Zoe', 'Kangoo', 'Master', 'Espace', 'Wind'],
  'Rimac': ['Concept One', 'Concept Two'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan'],
  'Rover': ['25', '45', '75', 'Streetwise', 'Mini', 'MG'],
  'Saab': ['900', '9000', '9-3', '9-5', '9-7X', '900 NG'],
  'Saipa': ['131', '141', '321', '512'],
  'Seat': ['Ibiza', 'Leon', 'Ateca', 'Arona', 'Tarraco', 'Alhambra', 'Toledo', 'Mii', 'Altea', 'Cordoba', 'Exeo'],
  'Shuanghuan': ['CEO', 'Automobile', 'Landwind'],
  'Singer': ['911'],
  'Škoda': ['Fabia', 'Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Scala', 'Rapid', 'Citigo', 'Yeti', 'Roomster', 'Enyaq', 'Combi', '120', '105'],
  'Smart': ['Fortwo', 'Forfour', 'Roadster'],
  'Spyker': ['C8', 'C12'],
  'SRT': ['Viper', 'Challenger', 'Charger'],
  'SSC': ['Ultimate Aero', 'Tuatara'],
  'Ssangyong': ['Actyon', 'Kyron', 'Rexton', 'Tivoli', 'Musso'],
  'Subaru': ['Impreza', 'Forester', 'Outback', 'XV', 'Legacy', 'Levorg', 'BRZ', 'Solterra', 'WRX', 'Libero'],
  'Suzuki': ['Alto', 'Celerio', 'Swift', 'Vitara', 'Ignis', 'S-Cross', 'Jimny', 'Grand Vitara', 'SX4', 'Kizashi', 'Splash'],
  'Tata': ['Nexon', 'Nexon EV', 'Tiago', 'Tigor', 'Tare', 'Safari', 'Harrier', 'Altroz'],
  'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  'Tianma': ['Kumquat', 'Seagull'],
  'Tiema': ['Shumai'],
  'Toyota': ['Aygo', 'Auris', 'Avensis', 'Avensis Verso', 'bZ4X', 'C-HR', 'Camry', 'Celica', 'Corolla', 'FJ Cruiser', 'GR Corolla', 'GR Supra', 'GR Yaris', 'Highlander', 'Hiace', 'Land Cruiser', 'Matrix', 'Mirai', 'Previa', 'Prius', 'Prius v', 'ProAce', 'ProAce City', 'RAV4', 'Sequoia', 'Sienna', 'Supra', 'Tacoma', 'Tarago', 'Tundra', 'Vellfire', 'Venza', 'Verso', 'Yaris', 'Alphard'],
  'Trabant': ['601', '1.1'],
  'Tramontana': ['R'],
  'Triumph': ['Spitfire', 'GT6', 'Stag', 'TR7'],
  'TVR': ['Sagaris', 'Griffith', 'Chimaera', 'Cerbera'],
  'Twike': ['3'],
  'Vandenbrink': ['Carver'],
  'Vanderhall': ['Venice', 'Laguna'],
  'Venturi': ['Fetish', 'Eclectic'],
  'Veritas': ['RS III'],
  'Volkswagen': ['Polo', 'Golf', 'Golf R', 'Golf GTI', 'Passat', 'Arteon', 'Tiguan', 'Taigo', 'Touran', 'Touareg', 'T-Cross', 'T-Roc', 'ID.3', 'ID.4', 'ID.5', 'ID.6', 'ID. Buzz', 'Caddy', 'Transporter', 'Multivan', 'Up', 'Jetta', 'Bora', 'Phaeton', 'Beetle'],
  'Volga': ['3110', 'Siber'],
  'Volvo': ['S60', 'S90', 'S40', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC70', 'XC90', 'C40', 'Polestar', 'P1800'],
  'Wiesmann': ['GT', 'MF4', 'MF5'],
  'Willys': ['Jeep', 'CJ'],
  'Wuling': ['Hongguang', 'Macaron'],
  'Xin': ['Changan'],
  'Zhonghua': ['Zunchi', 'Auchan'],
  'Zotye': ['T200', 'T300', 'T500', 'T600', 'Z500'],
};

export const VEHICLE_COLORS = [
  'Black', 'White', 'Silver', 'Gray', 'Blue', 'Red', 'Green', 
  'Brown', 'Beige', 'Gold', 'Orange', 'Yellow', 'Purple'
].sort();

export const ENGINE_SIZES = [
  '1.0L', '1.2L', '1.4L', '1.5L', '1.6L', '1.8L', '2.0L', 
  '2.2L', '2.4L', '2.5L', '2.7L', '3.0L', '3.5L', '4.0L',
  '1.0L TSI', '1.4L TFSI', '1.6L TDI', '2.0L TDI', '2.0L TFSI',
  '3.0L TDI', 'Electric', 'Hybrid'
].sort();

export const FUEL_TYPES = [
  'Petrol', 'Diesel', 'Hybrid', 'Electric', 'LPG', 'CNG'
];

export const TRANSMISSION_TYPES = [
  'Manual', 'Automatic', 'CVT', 'Semi-automatic'
];